notifications:
  email:
    on_success: change
    on_failure: change
dist: bionic
sudo: false
language: python
cache: pip
python:
  - 3.6
  - 3.7
addons:
  apt:
    packages:
      - qemu-system-i386
      - qemu-utils
install:
  - pip install -U -r requirements.tests.txt
  - pip install -e .
script:
  - pylint librouteros
  - yapf -dr librouteros
  - yapf -dr tests
  - wget --quiet netng.pl/routeros_test_images/routeros_6.33.3.qcow2 -O images/routeros_6.33.3.qcow2
  - wget --quiet netng.pl/routeros_test_images/routeros_6.43rc21.qcow2 -O images/routeros_6.43rc21.qcow2
  - py.test
deploy:
  provider: pypi
  user: lkostka
  password: $PYPI_PASS
  on:
    tags: true
    python: 3.8
